# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'add_service.ui'
#
# Created by: PyQt5 UI code generator 5.15.5
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Add_servis(object):
    def setupUi(self, Add_servis):
        Add_servis.setObjectName("Add_servis")
        Add_servis.resize(346, 163)
        self.Line_edit_price_service = QtWidgets.QLineEdit(Add_servis)
        self.Line_edit_price_service.setGeometry(QtCore.QRect(30, 40, 111, 21))
        self.Line_edit_price_service.setObjectName("Line_edit_price_service")
        self.Confirm_add_servis = QtWidgets.QPushButton(Add_servis)
        self.Confirm_add_servis.setGeometry(QtCore.QRect(220, 80, 93, 81))
        self.Confirm_add_servis.setObjectName("Confirm_add_servis")
        self.label_servis_price = QtWidgets.QLabel(Add_servis)
        self.label_servis_price.setGeometry(QtCore.QRect(10, 10, 171, 20))
        self.label_servis_price.setObjectName("label_servis_price")
        self.label_error_price_servis = QtWidgets.QLabel(Add_servis)
        self.label_error_price_servis.setGeometry(QtCore.QRect(20, 70, 131, 20))
        self.label_error_price_servis.setText("")
        self.label_error_price_servis.setObjectName("label_error_price_servis")
        self.timeEdit = QtWidgets.QTimeEdit(Add_servis)
        self.timeEdit.setGeometry(QtCore.QRect(30, 130, 121, 22))
        self.timeEdit.setObjectName("timeEdit")
        self.label_time_servis = QtWidgets.QLabel(Add_servis)
        self.label_time_servis.setGeometry(QtCore.QRect(14, 100, 161, 20))
        self.label_time_servis.setObjectName("label_time_servis")

        self.retranslateUi(Add_servis)
        QtCore.QMetaObject.connectSlotsByName(Add_servis)

    def retranslateUi(self, Add_servis):
        _translate = QtCore.QCoreApplication.translate
        Add_servis.setWindowTitle(_translate("Add_servis", "Add_servis"))
        self.Confirm_add_servis.setText(_translate("Add_servis", "Подтвердить"))
        self.label_servis_price.setText(_translate("Add_servis", "Введите ценник услуги:"))
        self.label_time_servis.setText(_translate("Add_servis", "Длительность процедуры:"))

        self.Confirm_add_servis.clicked.connect(self.add_serv)
    def add_serv(self):
        if self.Line_edit_price_service.text().isdigit() == True:
            pass
        else:
            self.Line_edit_price_service.setText('цифры тут!')



if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    Add_servis = QtWidgets.QDialog()
    ui = Ui_Add_servis()
    ui.setupUi(Add_servis)
    Add_servis.show()
    sys.exit(app.exec_())
