# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'add_service.ui'
#
# Created by: PyQt5 UI code generator 5.15.5
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Add_servis(object):
    def setupUi(self, Add_servis):
        Add_servis.setObjectName("Add_servis")
        Add_servis.resize(482, 163)
        self.Line_edit_name_service = QtWidgets.QLineEdit(Add_servis)
        self.Line_edit_name_service.setGeometry(QtCore.QRect(30, 40, 191, 41))
        self.Line_edit_name_service.setObjectName("Line_edit_name_service")
        self.Confirm_add_servis = QtWidgets.QPushButton(Add_servis)
        self.Confirm_add_servis.setGeometry(QtCore.QRect(350, 70, 93, 81))
        self.Confirm_add_servis.setObjectName("Confirm_add_servis")
        self.label_servis = QtWidgets.QLabel(Add_servis)
        self.label_servis.setGeometry(QtCore.QRect(40, 10, 171, 20))
        self.label_servis.setObjectName("label_servis")
        self.label_servis_data_time = QtWidgets.QLabel(Add_servis)
        self.label_servis_data_time.setGeometry(QtCore.QRect(40, 100, 181, 20))
        self.label_servis_data_time.setObjectName("label_servis_data_time")
        self.comboBox = QtWidgets.QComboBox(Add_servis)
        self.comboBox.setGeometry(QtCore.QRect(30, 130, 191, 22))
        self.comboBox.setEditable(True)
        self.comboBox.setObjectName("comboBox")

        self.retranslateUi(Add_servis)
        QtCore.QMetaObject.connectSlotsByName(Add_servis)

    def retranslateUi(self, Add_servis):
        _translate = QtCore.QCoreApplication.translate
        Add_servis.setWindowTitle(_translate("Add_servis", "Add_servis"))
        self.Confirm_add_servis.setText(_translate("Add_servis", "Подтвердить"))
        self.label_servis.setText(_translate("Add_servis", "Введите название услуги"))
        self.label_servis_data_time.setText(_translate("Add_servis", "Выберите профобласть:"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    Add_servis = QtWidgets.QDialog()
    ui = Ui_Add_servis()
    ui.setupUi(Add_servis)
    Add_servis.show()
    sys.exit(app.exec_())
