# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'add_doctor.ui'
#
# Created by: PyQt5 UI code generator 5.15.5
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Add_doctor(object):
    def setupUi(self, Add_doctor):
        Add_doctor.setObjectName("Add_doctor")
        Add_doctor.resize(487, 177)
        self.Confirm_add_doctor = QtWidgets.QPushButton(Add_doctor)
        self.Confirm_add_doctor.setGeometry(QtCore.QRect(380, 70, 93, 71))
        self.Confirm_add_doctor.setObjectName("Confirm_add_doctor")
        self.lineEdit = QtWidgets.QLineEdit(Add_doctor)
        self.lineEdit.setGeometry(QtCore.QRect(20, 40, 141, 22))
        self.lineEdit.setObjectName("lineEdit")
        self.lineEdit_phone_num_doctor = QtWidgets.QLineEdit(Add_doctor)
        self.lineEdit_phone_num_doctor.setGeometry(QtCore.QRect(210, 40, 141, 22))
        self.lineEdit_phone_num_doctor.setObjectName("lineEdit_phone_num_doctor")
        self.label_doctor_name = QtWidgets.QLabel(Add_doctor)
        self.label_doctor_name.setGeometry(QtCore.QRect(24, 10, 141, 20))
        self.label_doctor_name.setObjectName("label_doctor_name")
        self.label_doctor_age = QtWidgets.QLabel(Add_doctor)
        self.label_doctor_age.setGeometry(QtCore.QRect(20, 90, 161, 20))
        self.label_doctor_age.setObjectName("label_doctor_age")
        self.label_position_doctor = QtWidgets.QLabel(Add_doctor)
        self.label_position_doctor.setGeometry(QtCore.QRect(214, 90, 151, 20))
        self.label_position_doctor.setObjectName("label_position_doctor")
        self.label_doct_phone_number = QtWidgets.QLabel(Add_doctor)
        self.label_doct_phone_number.setGeometry(QtCore.QRect(214, 10, 191, 20))
        self.label_doct_phone_number.setObjectName("label_doct_phone_number")
        self.label_error_name_doctor = QtWidgets.QLabel(Add_doctor)
        self.label_error_name_doctor.setGeometry(QtCore.QRect(20, 70, 141, 20))
        self.label_error_name_doctor.setText("")
        self.label_error_name_doctor.setObjectName("label_error_name_doctor")
        self.label_error_phone_number_doctor = QtWidgets.QLabel(Add_doctor)
        self.label_error_phone_number_doctor.setGeometry(QtCore.QRect(210, 70, 141, 20))
        self.label_error_phone_number_doctor.setText("")
        self.label_error_phone_number_doctor.setObjectName("label_error_phone_number_doctor")
        self.comboBox = QtWidgets.QComboBox(Add_doctor)
        self.comboBox.setGeometry(QtCore.QRect(210, 120, 141, 22))
        self.comboBox.setEditable(True)
        self.comboBox.setObjectName("comboBox")
        self.dateEdit = QtWidgets.QDateEdit(Add_doctor)
        self.dateEdit.setGeometry(QtCore.QRect(20, 120, 151, 22))
        self.dateEdit.setObjectName("dateEdit")

        self.retranslateUi(Add_doctor)
        QtCore.QMetaObject.connectSlotsByName(Add_doctor)

    def retranslateUi(self, Add_doctor):
        _translate = QtCore.QCoreApplication.translate
        Add_doctor.setWindowTitle(_translate("Add_doctor", "Add_doctor"))
        self.Confirm_add_doctor.setText(_translate("Add_doctor", "Подтвердить"))
        self.lineEdit_phone_num_doctor.setText(_translate("Add_doctor", "375"))
        self.label_doctor_name.setText(_translate("Add_doctor", "Введите имя доктора:"))
        self.label_doctor_age.setText(_translate("Add_doctor", "Дата рождения доктора:"))
        self.label_position_doctor.setText(_translate("Add_doctor", "Укажите профобласть:"))
        self.label_doct_phone_number.setText(_translate("Add_doctor", "Укажите телефонный номер:"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    Add_doctor = QtWidgets.QDialog()
    ui = Ui_Add_doctor()
    ui.setupUi(Add_doctor)
    Add_doctor.show()
    sys.exit(app.exec_())
