# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'add_zapis.ui'
#
# Created by: PyQt5 UI code generator 5.15.5
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Zapis(object):
    def setupUi(self, Zapis):
        Zapis.setObjectName("Zapis")
        Zapis.resize(579, 252)
        self.comboBox_service = QtWidgets.QComboBox(Zapis)
        self.comboBox_service.setGeometry(QtCore.QRect(10, 40, 161, 22))
        self.comboBox_service.setEditable(True)
        self.comboBox_service.setObjectName("comboBox_service")
        self.label_choise_service = QtWidgets.QLabel(Zapis)
        self.label_choise_service.setGeometry(QtCore.QRect(14, 10, 151, 20))
        self.label_choise_service.setObjectName("label_choise_service")
        self.comboBox_doctors = QtWidgets.QComboBox(Zapis)
        self.comboBox_doctors.setGeometry(QtCore.QRect(190, 40, 161, 22))
        self.comboBox_doctors.setEditable(True)
        self.comboBox_doctors.setObjectName("comboBox_doctors")
        self.label_choice_doctor = QtWidgets.QLabel(Zapis)
        self.label_choice_doctor.setGeometry(QtCore.QRect(194, 10, 151, 20))
        self.label_choice_doctor.setObjectName("label_choice_doctor")
        self.comboBox_data_time = QtWidgets.QComboBox(Zapis)
        self.comboBox_data_time.setGeometry(QtCore.QRect(380, 40, 161, 22))
        self.comboBox_data_time.setEditable(True)
        self.comboBox_data_time.setObjectName("comboBox_data_time")
        self.label_choice_data_time = QtWidgets.QLabel(Zapis)
        self.label_choice_data_time.setGeometry(QtCore.QRect(384, 10, 151, 20))
        self.label_choice_data_time.setObjectName("label_choice_data_time")
        self.Confirm_zapis = QtWidgets.QPushButton(Zapis)
        self.Confirm_zapis.setGeometry(QtCore.QRect(470, 170, 93, 71))
        self.Confirm_zapis.setObjectName("Confirm_zapis")

        self.retranslateUi(Zapis)
        QtCore.QMetaObject.connectSlotsByName(Zapis)

    def retranslateUi(self, Zapis):
        _translate = QtCore.QCoreApplication.translate
        Zapis.setWindowTitle(_translate("Zapis", "Zapis"))
        self.label_choise_service.setText(_translate("Zapis", "Выберите услугу:"))
        self.label_choice_doctor.setText(_translate("Zapis", "Выберите доктора:"))
        self.label_choice_data_time.setText(_translate("Zapis", "Выберите дату и время:"))
        self.Confirm_zapis.setText(_translate("Zapis", "Подтвердить"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    Zapis = QtWidgets.QDialog()
    ui = Ui_Zapis()
    ui.setupUi(Zapis)
    Zapis.show()
    sys.exit(app.exec_())
