# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'main_w.ui'
#
# Created by: PyQt5 UI code generator 5.15.5
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets
from list_w import Ui_list
from FUNCTION import return_table




class Ui_Main_window(object):
    def setupUi(self, Main_window):
        Main_window.setObjectName("Main_window")
        Main_window.resize(627, 246)
        self.servis = QtWidgets.QPushButton(Main_window)
        self.servis.setGeometry(QtCore.QRect(30, 130, 121, 91))
        self.servis.setObjectName("servis")
        self.doctors = QtWidgets.QPushButton(Main_window)
        self.doctors.setGeometry(QtCore.QRect(180, 130, 121, 91))
        self.doctors.setObjectName("doctors")
        self.clients = QtWidgets.QPushButton(Main_window)
        self.clients.setGeometry(QtCore.QRect(340, 130, 121, 91))
        self.clients.setObjectName("clients")
        self.zapis = QtWidgets.QPushButton(Main_window)
        self.zapis.setGeometry(QtCore.QRect(490, 130, 121, 91))
        self.zapis.setObjectName("zapis")

        self.retranslateUi(Main_window)
        QtCore.QMetaObject.connectSlotsByName(Main_window)

    def retranslateUi(self, Main_window):
        _translate = QtCore.QCoreApplication.translate
        Main_window.setWindowTitle(_translate("Main_window", "main_windw"))
        self.servis.setText(_translate("Main_window", "Услуги"))
        self.doctors.setText(_translate("Main_window", "Врачи"))
        self.clients.setText(_translate("Main_window", "Клиенты"))
        self.zapis.setText(_translate("Main_window", "Запись"))

        self.servis.clicked.connect(self.servis_)
        self.doctors.clicked.connect(self.doctors_)
        self.clients.clicked.connect(self.clients_)
        self.zapis.clicked.connect(self.zapis_)

    def servis_(self):
        name_cols = ['id', 'name', 'price', 'time']
        tbl = return_table('SERVICE')
        app2 = QtWidgets.QDialog()
        ui2 = Ui_list()
        ui2.setupUi(app2)
        ui2.tableWidget.setColumnCount(len(name_cols))
        ui2.tableWidget.setRowCount(len(tbl.fetchall()))
        ui2.tableWidget.setHorizontalHeaderLabels(name_cols)
        tbl = return_table('SERVICE')

        index_row = 0

        for tuuple in tbl.fetchall():
            index_cow = 0
            for obj in tuuple:
                ui2.tableWidget.setItem(index_row, index_cow, QtWidgets.QTableWidgetItem(str(obj)))
                index_cow += 1
            index_row += 1

            # ui2.tableWidget.setItem(index_row,index_cow,QtWidgets.QTableWidgetItem(x[index_obj]))
            # index_cow+=1
            # index_obj+=1
            # print(x)

        # ui2.tableWidget.setRowCount(2)
        # ui2.tableWidget.setColumnCount(3)
        # ui2.tableWidget.setHorizontalHeaderLabels(["Name", "Hex Code", "Color"])
        app2.show()
        app2.exec_()

    def doctors_(self):
        name_cols = ['id', 'name', 'year', 'phone','position']
        tbl = return_table('EMPLOYERS')
        app2 = QtWidgets.QDialog()
        ui2 = Ui_list()
        ui2.setupUi(app2)
        ui2.tableWidget.setColumnCount(len(name_cols))
        ui2.tableWidget.setRowCount(len(tbl.fetchall()))
        ui2.tableWidget.setHorizontalHeaderLabels(name_cols)
        tbl = return_table('EMPLOYERS')

        index_row = 0

        for tuuple in tbl.fetchall():
            index_cow = 0
            for obj in tuuple:
                ui2.tableWidget.setItem(index_row, index_cow, QtWidgets.QTableWidgetItem(str(obj)))
                index_cow += 1
            index_row += 1

        app2.show()
        app2.exec_()

    def clients_(self):
        name_cols = ['id', 'name', 'age', 'phone']
        tbl = return_table('CLIENT_BASE')
        app2 = QtWidgets.QDialog()
        ui2 = Ui_list()
        ui2.setupUi(app2)
        ui2.tableWidget.setColumnCount(len(name_cols))
        ui2.tableWidget.setRowCount(len(tbl.fetchall()))
        ui2.tableWidget.setHorizontalHeaderLabels(name_cols)
        tbl = return_table('CLIENT_BASE')

        index_row = 0

        for tuuple in tbl.fetchall():
            index_cow = 0
            for obj in tuuple:
                ui2.tableWidget.setItem(index_row, index_cow, QtWidgets.QTableWidgetItem(str(obj)))
                index_cow += 1
            index_row += 1

        app2.show()
        app2.exec_()

    def zapis_(self):
        name_cols = ['id', 'client', 'servis', 'doctor','time']
        tbl = return_table('ORDERS')
        app2 = QtWidgets.QDialog()
        ui2 = Ui_list()
        ui2.setupUi(app2)
        ui2.tableWidget.setColumnCount(len(name_cols))
        ui2.tableWidget.setRowCount(len(tbl.fetchall()))
        ui2.tableWidget.setHorizontalHeaderLabels(name_cols)
        tbl = return_table('ORDERS')

        index_row = 0

        for tuuple in tbl.fetchall():
            index_cow = 0
            for obj in tuuple:
                ui2.tableWidget.setItem(index_row, index_cow, QtWidgets.QTableWidgetItem(str(obj)))
                index_cow += 1
            index_row += 1

        app2.show()
        app2.exec_()


if __name__ == "__main__":
    import sys

    app = QtWidgets.QApplication(sys.argv)
    Main_window = QtWidgets.QDialog()
    ui = Ui_Main_window()
    ui.setupUi(Main_window)
    Main_window.show()
    sys.exit(app.exec_())
