# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'main_w.ui'
#
# Created by: PyQt5 UI code generator 5.15.5
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets
from list_w import Ui_list
from FUNCTION import return_table


class Ui_Main_window(object):
    def setupUi(self, Main_window):
        Main_window.setObjectName("Main_window")
        Main_window.resize(627, 246)
        self.servis = QtWidgets.QPushButton(Main_window)
        self.servis.setGeometry(QtCore.QRect(30, 130, 121, 91))
        self.servis.setObjectName("servis")
        self.doctors = QtWidgets.QPushButton(Main_window)
        self.doctors.setGeometry(QtCore.QRect(180, 130, 121, 91))
        self.doctors.setObjectName("doctors")
        self.clients = QtWidgets.QPushButton(Main_window)
        self.clients.setGeometry(QtCore.QRect(340, 130, 121, 91))
        self.clients.setObjectName("clients")
        self.zapis = QtWidgets.QPushButton(Main_window)
        self.zapis.setGeometry(QtCore.QRect(490, 130, 121, 91))
        self.zapis.setObjectName("zapis")

        self.retranslateUi(Main_window)
        QtCore.QMetaObject.connectSlotsByName(Main_window)

    def retranslateUi(self, Main_window):
        _translate = QtCore.QCoreApplication.translate
        Main_window.setWindowTitle(_translate("Main_window", "main_windw"))
        self.servis.setText(_translate("Main_window", "Услуги"))
        self.doctors.setText(_translate("Main_window", "Врачи"))
        self.clients.setText(_translate("Main_window", "Клиенты"))
        self.zapis.setText(_translate("Main_window", "Запись"))

        self.servis.clicked.connect(self.servis_)
        self.doctors.clicked.connect(self.doctors_)
        self.clients.clicked.connect(self.clients_)
        self.zapis.clicked.connect(self.zapis_)

    def ggg(self, who):
        tbl = return_table(who)

        app2 = QtWidgets.QDialog()
        ui2 = Ui_list()
        ui2.setupUi(app2)
        ui2.tableWidget.setColumnCount(len(tbl[1]))
        tbl = return_table(who)
        ui2.tableWidget.setRowCount(len(tbl[0].fetchall()))
        tbl = return_table(who)
        ui2.tableWidget.setHorizontalHeaderLabels(tbl[1])
        tbl = return_table(who)

        index_row = 0

        for tuuple in tbl[0].fetchall():
            index_cow = 0
            for obj in tuuple:
                ui2.tableWidget.setItem(index_row, index_cow, QtWidgets.QTableWidgetItem(str(obj)))
                index_cow += 1
            index_row += 1

        app2.show()
        app2.exec_()

    def fff(self, servis=False, doctor=False, zapis=False, client=False):
        m = ['SERVICE', 'EMPLOYERS', 'CLIENT_BASE', 'ORDERS']
        if servis == True:
            self.ggg(m[0])

        elif doctor == True:
            self.ggg(m[1])

        elif client == True:
            self.ggg(m[2])

        elif zapis == True:
            self.ggg(m[3])

        else:
            return None

    def servis_(self):
        self.fff(servis=True)

    def doctors_(self):
        self.fff(doctor=True)

    def clients_(self):
        self.fff(client=True)

    def zapis_(self):
        self.fff(zapis=True)


if __name__ == "__main__":
    import sys

    app = QtWidgets.QApplication(sys.argv)
    Main_window = QtWidgets.QDialog()
    ui = Ui_Main_window()
    ui.setupUi(Main_window)
    Main_window.show()
    sys.exit(app.exec_())
