# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'Translation.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets
import googletrans
from googletrans import Translator
translator = Translator()

def worker():
    if ui.textEdit.toPlainText() != 'Введите что-то':
        x = len(ui.textEdit.toPlainText())
        w = len(ui.textEdit.toPlainText().split(' '))
        ui.plainTextEdit3.setPlainText(ui.textEdit.toPlainText())
        if ui.caps_flag:
            ui.plainTextEdit2.setPlainText(ui.plainTextEdit2.toPlainText().upper())

class Ui_MainWindow(object):
    b_flag = False
    caps_flag = False
    url_flag = False
    lan_flag = False
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(790, 318)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.lineEdit = QtWidgets.QLineEdit(self.centralwidget)
        self.lineEdit.setGeometry(QtCore.QRect(400, 20, 371, 101))
        self.lineEdit.setObjectName("lineEdit")
        self.pushButton = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton.setGeometry(QtCore.QRect(110, 210, 151, 41))
        self.pushButton.setObjectName("pushButton")
        self.radioButton = QtWidgets.QRadioButton(self.centralwidget)
        self.radioButton.setGeometry(QtCore.QRect(20, 20, 95, 20))
        self.radioButton.setObjectName("radioButton")
        self.radioButton_2 = QtWidgets.QRadioButton(self.centralwidget)
        self.radioButton_2.setGeometry(QtCore.QRect(20, 40, 95, 20))
        self.radioButton_2.setObjectName("radioButton_2")
        self.radioButton_3 = QtWidgets.QRadioButton(self.centralwidget)
        self.radioButton_3.setGeometry(QtCore.QRect(20, 60, 95, 20))
        self.radioButton_3.setObjectName("radioButton_3")
        self.checkBox = QtWidgets.QCheckBox(self.centralwidget)
        self.checkBox.setGeometry(QtCore.QRect(150, 20, 81, 20))
        self.checkBox.setObjectName("checkBox")
        self.checkBox_2 = QtWidgets.QCheckBox(self.centralwidget)
        self.checkBox_2.setGeometry(QtCore.QRect(150, 40, 131, 20))
        self.checkBox_2.setObjectName("checkBox_2")
        self.checkBox_3 = QtWidgets.QCheckBox(self.centralwidget)
        self.checkBox_3.setGeometry(QtCore.QRect(150, 60, 151, 20))
        self.checkBox_3.setObjectName("checkBox_3")
        self.textEdit = QtWidgets.QTextEdit(self.centralwidget)
        self.textEdit.setGeometry(QtCore.QRect(20, 100, 331, 91))
        self.textEdit.setObjectName("textEdit")
        self.textEdit_2 = QtWidgets.QTextEdit(self.centralwidget)
        self.textEdit_2.setGeometry(QtCore.QRect(400, 130, 371, 111))
        self.textEdit_2.setObjectName("textEdit_2")
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 790, 26))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.pushButton.setText(_translate("MainWindow", "Перевести"))
        self.radioButton.setText(_translate("MainWindow", "EN"))
        self.radioButton_2.setText(_translate("MainWindow", "FR"))
        self.radioButton_3.setText(_translate("MainWindow", "RU"))
        self.checkBox.setText(_translate("MainWindow", "CapsLock"))
        self.checkBox_2.setText(_translate("MainWindow", "Сделать жирным"))
        self.checkBox_3.setText(_translate("MainWindow", "Сделать курсивным"))
        self.textEdit.setHtml(_translate("MainWindow", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"</style></head><body style=\" font-family:\'MS Shell Dlg 2\'; font-size:7.8pt; font-weight:400; font-style:normal;\">\n"
"<p align=\"center\" style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\">Введите текст</p></body></html>"))

        self.checkBox.clicked.connect(self.caps_flag_d)
        self.checkBox_2.clicked.connect(self.c_flag_d)
        self.checkBox_3.clicked.connect(self.b_flag_d)
        self.radioButton.clicked.connect(self.en_flag)
        self.radioButton_2.clicked.connect(self.fr_flag)
        self.radioButton_3.clicked.connect(self.ru_flag)

    def caps_flag_d(self):
        if self.caps_flag:
            self.caps_flag = False
        else:
            self.caps_flag = True

    def c_flag_d(self):
        if self.c_flag:
            self.c_flag = False
        else:
            self.c_flag = True

    def b_flag_d(self):
        if self.b_flag:
            self.b_flag = False
        else:
            self.b_flag = True

    def en_flag(self):
        self.lang = 'en'
        self.lan_flag = True

    def fr_flag(self):
        self.lang = 'fr'
        self.lan_flag = True

    def ru_flag(self):
        self.lang = 'ru'
        self.lan_flag = True
if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())
